DELETE FROM answers;
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (1, 'Stockholm', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (1, 'Oslo', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (1, 'Göteborg', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (1, 'Malmö', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (2, 'Stockholm', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (2, 'Oslo', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (2, 'Gothenburg', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (2, 'Malmo', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (3, 'Zebra', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (3, 'Lejon', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (3, 'Elefant', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (3, 'Pingvin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (4, 'Zebra', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (4, 'Lion', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (4, 'Elephant', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (4, 'Penguin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (5, 'Venus', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (5, 'Mars', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (5, 'Merkurius', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (5, 'Jupiter', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (6, 'Venus', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (6, 'Mars', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (6, 'Mercury', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (6, 'Jupiter', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (7, 'Snövit', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (7, 'Cinderella', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (7, 'Törnrosa', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (7, 'Rapunzel', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (8, 'Snow White', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (8, 'Cinderella', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (8, 'Sleeping Beauty', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (8, 'Rapunzel', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (9, 'Banan', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (9, 'Jordgubb', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (9, 'Apelsin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (9, 'Vindruvor', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (10, 'Banana', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (10, 'Strawberry', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (10, 'Orange', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (10, 'Grapes', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (11, 'Valp', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (11, 'Kattunge', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (11, 'Unge', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (11, 'Kalv', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (12, 'Pup', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (12, 'Kitten', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (12, 'Cub', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (12, 'Calf', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (13, 'Sommar', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (13, 'Vår', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (13, 'Höst', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (13, 'Monsun', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (14, 'Summer', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (14, 'Spring', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (14, 'Fall', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (14, 'Monsoon', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (15, 'Lejon', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (15, 'Elefant', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (15, 'Pingvin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (15, 'Fladdermus', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (16, 'Lion', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (16, 'Elephant', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (16, 'Penguin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (16, 'Bat', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (17, 'Sex', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (17, 'Åtta', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (17, 'Tio', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (17, 'Tolv', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (18, 'Six', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (18, 'Eight', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (18, 'Ten', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (18, 'Twelve', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (19, 'Teleskop', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (19, 'Mikroskop', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (19, 'Kalejdoskop', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (19, 'Periskop', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (20, 'Telescope', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (20, 'Microscope', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (20, 'Kaleidoscope', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (20, 'Periscope', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (21, 'Morot', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (21, 'Selleri', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (21, 'Chili', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (21, 'Potatis', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (22, 'Carrot', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (22, 'Celery', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (22, 'Chilli', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (22, 'Potato', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (23, 'William Shakespeare', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (23, 'Charles Dickens', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (23, 'Jane Austen', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (23, 'Mark Twain', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (24, 'William Shakespeare', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (24, 'Charles Dickens', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (24, 'Jane Austen', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (24, 'Mark Twain', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (25, 'Au', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (25, 'Ag', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (25, 'Fe', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (25, 'Cu', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (26, 'Au', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (26, 'Ag', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (26, 'Fe', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (26, 'Cu', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (27, 'Venus', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (27, 'Jupiter', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (27, 'Mars', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (27, 'Saturnus', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (28, 'Venus', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (28, 'Jupiter', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (28, 'Mars', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (28, 'Saturn', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (29, '1945', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (29, '1939', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (29, '1955', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (29, '1960', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (30, '1945', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (30, '1939', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (30, '1955', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (30, '1960', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (31, 'Leonardo da Vinci', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (31, 'Vincent van Gogh', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (31, 'Pablo Picasso', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (31, 'Michelangelo', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (32, 'Leonardo da Vinci', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (32, 'Vincent van Gogh', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (32, 'Pablo Picasso', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (32, 'Michelangelo', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (33, 'Afrikansk elefant', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (33, 'Isbjörn', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (33, 'Giraff', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (33, 'Blåval', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (34, 'African elephant', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (34, 'Polar bear', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (34, 'Giraffe', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (34, 'Blue whale', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (35, 'Japan', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (35, 'Kina', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (35, 'Sydkorea', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (35, 'Thailand', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (36, 'Japan', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (36, 'China', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (36, 'South Korea', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (36, 'Thailand', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (37, 'George Washington', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (37, 'Thomas Jefferson', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (37, 'Abraham Lincoln', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (37, 'John Adams', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (38, 'George Washington', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (38, 'Thomas Jefferson', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (38, 'Abraham Lincoln', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (38, 'John Adams', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (39, 'Paris', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (39, 'Rom', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (39, 'Madrid', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (39, 'Berlin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (40, 'Paris', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (40, 'Rome', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (40, 'Madrid', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (40, 'Berlin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (41, 'Koppar', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (41, 'Silver', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (41, 'Guld', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (41, 'Järn', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (42, 'Copper', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (42, 'Silver', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (42, 'Gold', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (42, 'Iron', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (43, 'Quasimodo', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (43, 'Buzz', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (43, 'Woody', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (43, 'Pinocchio', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (44, 'Quasimodo', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (44, 'Buzz', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (44, 'Woody', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (44, 'Pinocchio', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (45, '6', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (45, '7', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (45, '8', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (45, '9', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (46, '6', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (46, '7', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (46, '8', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (46, '9', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (47, 'Abborre', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (47, 'Clownfisk', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (47, 'Tonfisk', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (47, 'Haj', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (48, 'Perch', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (48, 'Clownfish', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (48, 'Tuna', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (48, 'Shark', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (49, '4', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (49, '5', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (49, '6', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (49, '7', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (50, '4', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (50, '5', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (50, '6', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (50, '7', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (51, 'USA', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (51, 'Nya Zealand', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (51, 'Australien', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (51, 'England', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (52, 'USA', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (52, 'New Zealand', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (52, 'Australia', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (52, 'England', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (53, 'Bambu', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (53, 'Sallad', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (53, 'Kött', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (53, 'Löv', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (54, 'Bamboo', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (54, 'Salad', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (54, 'Meat', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (54, 'Leaves', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (55, '3', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (55, '5', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (55, '7', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (55, '9', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (56, '3', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (56, '5', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (56, '7', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (56, '9', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (57, 'Quasimodo', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (57, 'Buzz', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (57, 'Woody', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (57, 'Pinocchio', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (58, 'Quasimodo', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (58, 'Buzz', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (58, 'Woody', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (58, 'Pinocchio', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (59, 'K2', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (59, 'Kebnekajse', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (59, 'Everest', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (59, 'Kilimanjaro', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (60, 'K2', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (60, 'Kebnekajse', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (60, 'Everest', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (60, 'Kilimanjaro', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (61, 'Sten', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (61, 'Trä', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (61, 'Järn', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (61, 'Diamant', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (62, 'Rock', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (62, 'Wood', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (62, 'Iron', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (62, 'Diamond', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (63, 'Delfin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (63, 'Segelfisk', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (63, 'Ål', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (63, 'Tonfisk', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (64, 'Dolphin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (64, 'Sailfish', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (64, 'Eel', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (64, 'Tuna', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (65, 'Apa', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (65, 'Hund', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (65, 'Katt', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (65, 'Kanin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (66, 'Chimpanzee', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (66, 'Dog', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (66, 'Cat', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (66, 'Bunny', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (67, 'En konstellation', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (67, 'En vagn', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (67, 'En målning', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (67, 'En stjärna', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (68, 'A constellation', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (68, 'A wagon', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (68, 'A painting', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (68, 'A star', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (69, 'Alligator', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (69, 'Krokodil', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (69, 'Babian', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (69, 'Flodhäst', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (70, 'Alligator', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (70, 'Crocodile', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (70, 'Baboon', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (70, 'Hippo', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (71, 'Flygande ekorre', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (71, 'Havsörn', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (71, 'Fladdermus', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (71, 'Stork', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (72, 'Flying squirrel', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (72, 'Bald eagle', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (72, 'Bat', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (72, 'Stork', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (73, 'Rovdjur', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (73, 'Växtätare', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (73, 'Allätare', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (73, 'Pescitarian', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (74, 'Carnivore', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (74, 'Herbivore', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (74, 'Omnivore', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (74, 'Pescitarian', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (75, 'Merkurius', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (75, 'Jorden', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (75, 'Neptunus', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (75, 'Jupiter', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (76, 'Mercury', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (76, 'Earth', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (76, 'Neptune', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (76, 'Jupiter', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (77, 'Tyfoner är starkare än Orkaner', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (77, 'Tyfon är på land, Orkan på Vatten', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (77, 'Orkaner rör sig långsammare', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (77, 'Inget förutom geografisk position', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (78, 'Typhoons are stronger than hurricanes', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (78, 'Typhoons happen over land; hurricanes over water', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (78, 'Hurricanes are slower-moving', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (78, 'Nothing except geographic position', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (79, 'Ben', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (79, 'Hår', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (79, 'Naglar', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (79, 'Tänder', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (80, 'Bone', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (80, 'Hair', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (80, 'Nails', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (80, 'Teeth', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (81, '501', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (81, '105', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (81, '206', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (81, '347', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (82, '501', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (82, '105', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (82, '206', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (82, '247', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (83, 'Alligator', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (83, 'Krokodil', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (83, 'Babian', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (83, 'Flodhäst', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (84, 'Alligator', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (84, 'Crocodile', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (84, 'Baboon', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (84, 'Hippo', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (85, 'Stilla havet', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (85, 'Atlanten', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (85, 'Indiska oceanen', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (85, 'Kaspiska havet', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (86, 'The Pacific ocean', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (86, 'The Atlantic ocean', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (86, 'The Indian ocean', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (86, 'The Caspian sea', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (87, '25 meter', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (87, '30 meter', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (87, '50 meter', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (87, '100 meter', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (88, '25 meters', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (88, '30 meters', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (88, '50 meters', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (88, '100 meters', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (89, 'Fobi för optiker', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (89, 'Fobi för hundar', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (89, 'Fobi för ankor', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (89, 'Fobi för vargar', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (90, 'Fear of opticians', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (90, 'Fear of dogs', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (90, 'Fear of ducks', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (90, 'Fear of wolves', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (91, 'Maria Göppert Mayer', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (91, 'Anne L´Huillier', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (91, 'Marie Curie', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (91, 'Donna Strickland', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (92, 'Maria Göppert Mayer', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (92, 'Anne L´Huillier', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (92, 'Marie Curie', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (92, 'Donna Strickland', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (93, 'Amelia Earhart', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (93, 'Barbara McClintock', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (93, 'Sally Ride', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (93, 'Bessica Raiche', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (94, 'Amelia Earhart', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (94, 'Barbara McClintock', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (94, 'Sally Ride', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (94, ' Bessica Raiche', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (95, 'Belgien', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (95, 'USA', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (95, 'Colombia', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (95, 'Schweiz', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (96, 'Belgium', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (96, 'USA', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (96, 'Colombia', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (96, 'Switzerland', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (97, 'Coca Cola', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (97, 'Te', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (97, 'Mjölk', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (97, 'Kaffe', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (98, 'Coca Cola', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (98, 'Tea', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (98, 'Milk', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (98, 'Coffee', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (99, 'Agnes och Matilda', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (99, 'Melinda och Anna', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (99, 'Anastasia och Drizella', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (99, 'Becky och Gloria', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (100, 'Agnes and Matilda', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (100, 'Melinda and Anna', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (100, 'Anastasia and Drizella', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (100, 'Becky and Gloria', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (101, 'Candle in the Wind - Elton John', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (101, 'White Christmas - Bing Crosby', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (101, 'I Will Always Love You- Whitney Houston', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (101, 'My Heart Will Go On - Celine Dion', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (102, 'Candle in the Wind - Elton John', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (102, 'White Christmas - Bing Crosby', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (102, 'I Will Always Love You- Whitney Houston', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (102, 'My Heart Will Go On - Celine Dion', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (103, 'Sverige', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (103, 'Finland', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (103, 'Ryssland', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (103, 'Kanada', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (104, 'Sweden', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (104, 'Finland', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (104, 'Russia', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (104, 'Canada', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (105, 'Kaskelot', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (105, 'Elefant', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (105, 'Påfågel', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (105, 'Hyena', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (106, 'Sperm Whale', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (106, 'Elephant', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (106, 'Peacock', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (106, 'Hyena', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (107, '90 mil', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (107, '9 mil', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (107, '1 mil', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (107, '55 mil', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (108, '90 miles', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (108, '9 miles', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (108, '1 miles', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (108, '55 miles', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (109, '2003', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (109, '2005', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (109, '2007', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (109, '2009', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (110, '2003', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (110, '2005', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (110, '2007', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (110, '2009', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (111, 'Alexander Fleming', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (111, 'Marie Curie', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (111, 'Louis Pasteur', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (111, 'Jonas Salk', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (112, 'Alexander Fleming', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (112, 'Marie Curie', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (112, 'Louis Pasteur', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (112, 'Jonas Salk', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (113, '6', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (113, '7', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (113, '8', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (113, '9', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (114, '6', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (114, '7', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (114, '8', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (114, '9', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (115, 'Novak Djokovic', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (115, 'Roger Federer', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (115, 'Björn Borg', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (115, 'Rafael Nadal', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (116, 'Novak Djokovic', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (116, 'Roger Federer', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (116, 'Björn Borg', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (116, 'Rafael Nadal', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (117, 'Ryssland och Kazakhstan', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (117, 'Argentina och Chile', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (117, 'Kina och Mogoliet', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (117, 'USA och Kanada', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (118, 'Russia and Kazakhstan', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (118, 'Argentina and Chile', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (118, 'China and Mongolia', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (118, 'USa and Canada', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (119, 'P.Diddy', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (119, 'TI', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (119, 'Childish Gambino', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (119, 'Ice Cube', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (120, 'P.Diddy', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (120, 'TI', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (120, 'Childish Gambino', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (120, 'Ice Cube', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (121, 'John Steinbeck', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (121, 'F.Scott Fitzgerald', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (121, 'Ernest Hemingway', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (121, 'Philip Roth', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (122, 'John Steinbeck', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (122, 'F.Scott Fitzgerald', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (122, 'Ernest Hemingway', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (122, 'Philip Roth', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (123, 'Thailand', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (123, 'Nepal', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (123, 'Kambodja', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (123, 'Indien', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (124, 'Thailand', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (124, 'Nepal', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (124, 'Cambodia', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (124, 'India', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (125, 'Richter', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (125, 'Scoville', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (125, 'Roentgen', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (125, 'Bar', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (126, 'Richter', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (126, 'Scoville', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (126, 'Roentgen', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (126, 'Bar', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (127, 'Mulan', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (127, 'Merida', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (127, 'Vaiana', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (127, 'Pocahontas', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (128, 'Mulan', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (128, 'Merida', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (128, 'Moana', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (128, 'Pocahontas', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (129, 'Aztekerna', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (129, 'Maya indianerna', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (129, 'Olmeker', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (129, 'Inkariket', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (130, 'Aztecs', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (130, 'Mayans', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (130, 'Olmecs', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (130, 'Incas', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (131, 'Vulkaniska', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (131, 'Elementära', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (131, 'Metamorfa', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (131, 'Sedimentära', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (132, 'Igneous', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (132, 'Elementary', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (132, 'Metamorphic', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (132, 'Sedimentary', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (133, 'Byzantine', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (133, 'Konstantinopel', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (133, 'Nicomedia', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (133, 'Stamboul', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (134, 'Byzantium', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (134, 'Constantinople', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (134, 'Nicomedia', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (134, 'Stamboul', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (135, 'Göta kanal', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (135, 'Nilen', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (135, 'Amazonfloden', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (135, 'Mississippi floden', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (136, 'Göta canal', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (136, 'The Nile', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (136, 'The Amazon river', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (136, 'The Mississippi river', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (137, 'Blåval', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (137, 'Elefant', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (137, 'Jättebläckfisk', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (137, 'Älg', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (138, 'Blue whale', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (138, 'Elephant', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (138, 'Giant squid', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (138, 'Elk', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (139, 'Spanska', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (139, 'Engelska', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (139, 'Mandarin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (139, 'Arabiska', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (140, 'Spanish', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (140, 'English', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (140, 'Mandarin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (140, 'Arabic', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (141, 'Havsörn', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (141, 'Struts', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (141, 'Fiskmås', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (141, 'Albatross', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (142, 'Bald eagle', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (142, 'Ostrich', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (142, 'Seagull', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (142, 'Albatross', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (143, 'New York', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (143, 'Los Angeles', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (143, 'Washington, D.C.', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (143, 'Miami', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (144, 'New York', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (144, 'Los Angeles', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (144, 'Washington, D.C.', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (144, 'Miami', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (145, 'Destiny Hope Cyrus', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (145, 'Noah Cyrus', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (145, 'Milena Cyrus', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (145, 'Brandi Cyrus', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (146, 'Destiny Hope Cyrus', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (146, 'Noah Cyrus', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (146, 'Milena Cyrus', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (146, 'Brandi Cyrus', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (147, 'Levern', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (147, 'Tjocktarmen', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (147, 'Huden', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (147, 'Lungorna', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (148, 'The Liver', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (148, 'The Long Intestine', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (148, 'The Skin', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (148, 'The Lungs', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (149, 'Coca Cola', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (149, 'Varm Choklad', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (149, 'Mjölk', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (149, 'Kaffe', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (150, 'Coca Cola', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (150, 'Hot Chocolate', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (150, 'Milk', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (150, 'Coffee', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (151, 'Monaco', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (151, 'Andorra', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (151, 'Vatikanstaten', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (151, 'Luxemburg', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (152, 'Monaco', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (152, 'Andorra', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (152, 'Vatican City', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (152, 'Luxembourg', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (153, '2', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (153, '3', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (153, '4', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (153, '5', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (154, '2', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (154, '3', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (154, '4', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (154, '5', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (155, 'Vit', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (155, 'Genomskinliga', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (155, 'Grå', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (155, 'Svart', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (156, 'White', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (156, 'Transparent', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (156, 'Gray', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (156, 'Black', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (157, 'Trummor', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (157, 'Harpa', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (157, 'Piano', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (157, 'Flöjt', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (158, 'Drums', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (158, 'Harp', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (158, 'Piano', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (158, 'Flute', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (159, 'Neil Armstrong', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (159, 'Buzz Aldrin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (159, 'Laika Ivanov', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (159, 'Yuri Gagarin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (160, 'Neil Armstrong', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (160, 'Buzz Aldrin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (160, 'Laika Ivanov', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (160, 'Yuri Gagarin', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (161, 'Norge', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (161, 'Danmark', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (161, 'Finland', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (161, 'Sverige', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (162, 'Norway', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (162, 'Danmark', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (162, 'Finland', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (162, 'Sweden', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (163, '12', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (163, '24', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (163, '36', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (163, '50', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (164, '12', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (164, '24', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (164, '36', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (164, '50', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (165, 'Pluto', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (165, 'Kalle Anka', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (165, 'Korv med bröd', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (165, 'Mimmi', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (166, 'Pluto', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (166, 'Donald Duck', false);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (166, 'Hot Dogs', true);
INSERT INTO answers (questions_id, answers_text, is_correct) VALUES (166, 'Minnie Mouse', false);





