DELETE FROM questions;
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Huvudstaden i Sverige?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Capital of Sweden?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket djur är känt för svart vita ränder?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What animal is known for its black and white stripes?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken planet är närmast solen?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which planet is closest to the Sun?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vad hette sagoprinsessan som sov i 100 år?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What is the name of the fairy tale character who slept for 100 years?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken frukt är röd och hjärtformad?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which fruit is red and heart-shaped?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vad kallas en ung hund?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What do you call a young dog?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken säsong kommer efter vinter?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What season comes after winter?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket av dessa djur kan flyga?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which of these animals can fly?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Hur många ben har en spindel vanligtvis?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'How many legs does a spider typically have?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket av dessa används för att se väldigt långt bort?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What do we use to see things far away?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken av dessa är en typ av frukt?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which of these is a type of fruit?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vem skrev pjäsen "Romeo och Julia?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Who wrote the play "Romeo and Juliet"?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vad är den kemiska beteckningen för guld?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'What is the chemical symbol for gold?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilken planet är känd som den "Röda planeten"?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Which planet is known as the "Red Planet"?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilket år slutade andra världskriget?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'In which year did World War II end?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vem målade Mona Lisa?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Who painted the Mona Lisa?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilket är det största däggdjuret på jorden?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'What is the largest mammal on Earth?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilket land är känt som soluppgångens land?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Which country is known as the Land of the Rising Sun?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vem var USAs första president?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Who was the first President of the United States?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Frankrikes huvudstad?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'What is the capital city of France?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilket element har atomnumret 79?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Which element has the atomic number 79?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vems näsa växer när den ljuger?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Whose nose grows when it tells lies?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Hur många planeter finns i vårt solsystem?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'How many planets are in our solar system?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vad är Nemo för typ av fisk?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What type of fish is Nemo?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Hur många färger har en Regnbåge?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'How many colors are in a rainbow?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'I vilket land hittar du en känguru?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'In which country would you find a kangaroo?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vad äter en panda?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What does a panda eat?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Hur många kontinenter finns det?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'How many continents are there in the world?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vems näsa växer när den ljuger?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Whose nose grows when it tells lies?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket är det högsta berget i världen?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What is the highest mountain on Earth?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vad är det hårdaste naturliga ämnet?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What is the hardest natural substance?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken är det snabbaste djuret i havet?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What is the fastest animal in the water?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket djur va först i rymden?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What animal was first in space?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vad är Karlavagnen för något?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What is the Big Dipper?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket land djur kan öppna sin mun mest?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What land animal can open its mouth the widest?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket är det enda flygande däggdjuret?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What is the only flying mammal?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vad kallas ett djur som äter både kött och grönsaker?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What is an animal called that eats both meat and plants?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken planet har den kortaste dagen?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What planet has the shortest day?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vad är skillnaden på en Orkan och en Tyfon?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What is the difference between a hurricane and a typhoon?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vad innehåller det hårdaste ämnet i människokroppen?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What contains the hardest substance in the human body?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Hur många ben finns i en vuxen kropp?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'How many bones are in the adult human body?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket land djur kan öppna sin mun mest?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What land animal can open its mouth the widest?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket hav är störst?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What Ocean is the largest?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Hur lång är en olympisk pool?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'How long is an Olympic swimming pool?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vad är Cynofobi?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'What is Cynophobia?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vem va första kvinnan att vinna noblepriset?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Who was the first woman to win the Nobel prize?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vem var första kvinnliga piloten att flyga solo äver Atlanten?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Who was the first woman pilot to fly solo across the Atlantic?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilket land konsumerar mest choklad per capita?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Which country consumes the most chocolate per capita?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilken är den mest konsumerade tillverkade drycken i världen?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'What is the most consumed manufactured drink in the world?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vad heter Askungens styvsystrar?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'What are the names of Cinderella’s stepsisters?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Högstsäljande musik singeln genom tiderna är?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'The biggest selling music single of all time is?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilket land har flest naturliga sjöar?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'What country has the most natural lakes?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilket är det mest högljudda djuret på jorden?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'What is the loudest animal on Earth?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Hur många mil är Nya Zealands Nittio Mil Strand?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'How long is New Zealand’s Ninety Mile Beach?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilket år släpptes den första modellen av iPhone?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'What year was the first model of the iPhone released?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vem upptäckte penicillin?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Who discovered penicillin?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'I hur många filmer spelade Sean Connery James Bond?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'How many films did Sean Connery play James Bond in?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vem har vunnit "the French Open" mest gånger(Tennis)?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Who has won "the French Open" more times(Tennis)?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilka två länder delar den längsta internationella gränsen?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Which two countries share the longest international border?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilket namn är rapartisten Sean Combs mer känd som?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Which name is rapper Sean Combs better known by?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vem skrev boken "Old Man and The Sea"?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Who wrote the book “Old Man and The Sea”?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vart sägs det Buddha föddes?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Buddha is claimed to have been born in what country?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilken skala används när man mäter hetta?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'What scale is used to measure spiciness?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken Disney prinsessa har en tatuering?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What Disney princess has a tattoo?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken uråldrig civilisation byggde Machu Picchu?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What ancient civilization built the Machu Picchu?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken av dessa 4 är INTE en typ av sten?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which of these 4 is NOT a type of rock?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken av dessa namn har Istanbul aldrig varit kännt som?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which of these names have Istanbul not been known by?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken är den längsta floden i världen?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which is the longest river in the world?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket djur har dom största ögonen?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which animal has the largest eyes?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket är det mest talade språket i världen?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which is the most spoken language?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken fågel har det längsta vingspannet?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which bird has the largest wingspan?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken stad är USAs huvudstad?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which city is the USAs capital?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vad heter Miley Cyrus egentligen?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What is Miley Cyrus´s real name?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket är det största organet?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which is your bodys largest organ?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Världens populäraste drink som inte är Alkohol?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What’s the most popular drink in the world that is not alcohol?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket är det minsta landet i världen?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which is the smallest country in the world?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Hur många magsäckar har en ko?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'How many compartments does a cow´s stomach have?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vad för färg är Isbjörnens päls?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What color fur does a polar bear have?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket är det äldsta funna instrumentet?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which is the oldest found instrument?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vem var första personen att gå på månen?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Who was the first person to walk on the Moon?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket skandinaviskt land är störst?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What is the largest country in Scandinavia?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Hur många ägg äter Gaston från "Skönheten och Odjuret"varje morgon?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'How many eggs does Gaston eat each morning in "Beauty and the Beast"?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilka var Musse Piggs första ord?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What were Mickey Mouse´s first words?');



