DELETE FROM questions;
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Huvudstaden i Sverige?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Capital of Sweden?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket djur är känt för svart vita ränder?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What animal is known for its black and white stripes?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken planet är närmast solen?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which planet is closest to the Sun?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vad hette sagoprinsessan som sov i 100 år?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What is the name of the fairy tale character who slept for 100 years?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken frukt är röd och hjärtformad?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which fruit is red and heart-shaped?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vad kallas en ung hund?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What do you call a young dog?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken säsong kommer efter vinter?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What season comes after winter?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket av dessa djur kan flyga?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which of these animals can fly?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Hur många ben har en spindel vanligtvis?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'How many legs does a spider typically have?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilket av dessa används för att se väldigt långt bort?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'What do we use to see things far away?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 1, 'Vilken av dessa är en typ av frukt?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (2, 2, 'Which of these is a type of fruit?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vem skrev pjäsen "Romeo och Julia?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Who wrote the play "Romeo and Juliet"?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vad är den kemiska beteckningen för guld?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'What is the chemical symbol for gold?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilken planet är känd som den "Röda planeten"?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Which planet is known as the "Red Planet"?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilket år slutade andra världskriget?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'In which year did World War II end?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vem målade Mona Lisa?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Who painted the Mona Lisa?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilket är det största däggdjuret på jorden?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'What is the largest mammal on Earth?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilket land är känt som soluppgångens land?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Which country is known as the Land of the Rising Sun?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vem var USAs första president?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Who was the first President of the United States?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Frankrikes huvudstad?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'What is the capital city of France?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 1, 'Vilket element har atomnumret 79?');
INSERT INTO questions (mode_id, language_id, question_text) VALUES (1, 2, 'Which element has the atomic number 79?');

